main_app/urls.py
from django.urls import path

from main_app.EditResultView import EditResultView

from . import hod_views, staff_views, student_views, views

urlpatterns = [
    path("", views.login_page, name='login_page'),
    path("get_attendance", views.get_attendance, name='get_attendance'),
    path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("logout_user/", views.logout_user, name='user_logout'),
    path("admin/home/", hod_views.admin_home, name='admin_home'),
    path("staff/add", hod_views.add_staff, name='add_staff'),
    path("branch/add", hod_views.add_branch, name='add_branch'),
    path("send_staff_notification/", hod_views.send_staff_notification,
         name='send_staff_notification'),
    path("add_session/", hod_views.add_session, name='add_session'),
   
    path("admin_notify_staff", hod_views.admin_notify_staff,
         name='admin_notify_staff'),
    path("admin_view_profile", hod_views.admin_view_profile,
         name='admin_view_profile'),
    path("check_email_availability", hod_views.check_email_availability,
         name="check_email_availability"),
    path("session/manage/", hod_views.manage_session, name='manage_session'),
    path("session/edit/<int:session_id>",
         hod_views.edit_session, name='edit_session'),
    path("staff/view/leave/", hod_views.view_staff_leave, name="view_staff_leave",),
    path("attendance/view/", hod_views.admin_view_attendance,
         name="admin_view_attendance",),
    path("results/view/", hod_views.admin_view_results,
         name="admin_view_results",),
    path("attendance/fetch/", hod_views.get_admin_attendance,
         name='get_admin_attendance'),
    path("student/add/", hod_views.add_student, name='add_student'),
    path("subject/add/", hod_views.add_subject, name='add_subject'),
    path("staff/manage/", hod_views.manage_staff, name='manage_staff'),
    path("student/manage/", hod_views.manage_student, name='manage_student'),
    path("branch/manage/", hod_views.manage_branch, name='manage_branch'),
    path("subject/manage/", hod_views.manage_subject, name='manage_subject'),
    path("staff/edit/<int:staff_id>", hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:staff_id>",
         hod_views.delete_staff, name='delete_staff'),

    path("branch/delete/<int:branch_id>",
         hod_views.delete_branch, name='delete_branch'),

    path("subject/delete/<int:subject_id>",
         hod_views.delete_subject, name='delete_subject'),

    path("session/delete/<int:session_id>",
         hod_views.delete_session, name='delete_session'),

    path("student/delete/<int:student_id>",
         hod_views.delete_student, name='delete_student'),
    path("student/edit/<int:student_id>",
         hod_views.edit_student, name='edit_student'),
    path("branch/edit/<int:branch_id>",
         hod_views.edit_branch, name='edit_branch'),
    path("subject/edit/<int:subject_id>",
         hod_views.edit_subject, name='edit_subject'),
     #realtime filtering of subjects in takeattendance
     path('get_filtered_subjects/<int:branch_id>/', 
          hod_views.get_filtered_subjects, name='get_filtered_subjects'),




    # Staff
    path("staff/home/", staff_views.staff_home, name='staff_home'),
    path("staff/apply/leave/", staff_views.staff_apply_leave,
         name='staff_apply_leave'),
    path("staff/view/profile/", staff_views.staff_view_profile,
         name='staff_view_profile'),
    path("staff/attendance/take/", staff_views.staff_take_attendance,
         name='staff_take_attendance'),
    path("staff/attendance/update/", staff_views.staff_update_attendance,
         name='staff_update_attendance'),
    path("staff/get_students/", staff_views.get_students, name='get_students'),
    path("staff/fetch_results/",staff_views.fetch_results,name='fetch_results'),
    path("staff/attendance/fetch/", staff_views.get_student_attendance,
         name='get_student_attendance'),
    path("staff/attendance/save/",
         staff_views.save_attendance, name='save_attendance'),
    #path("staff/attendance/update/",
         #staff_views.update_attendance, name='update_attendance'),
    path("staff/attendance/report/",
         staff_views.staff_attendance_report, name='staff_attendance_report'),
    path("staff/fcmtoken/", staff_views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/", staff_views.staff_view_notification,
         name="staff_view_notification"),
    path("staff/result/add/", staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/", EditResultView.as_view(),
         name='edit_student_result'),
    path('staff/result/fetch/', staff_views.fetch_student_result,
         name='fetch_student_result'),
    path('staff/result/report/',
         staff_views.staff_marks_report, name='staff_marks_report'),
     path('staff/result/midterms/',
         staff_views.staff_midterm_report, name='staff_midterm_report'),


    # Student
    path("student/home/", student_views.student_home, name='student_home'),
    path("student/view/attendance/", student_views.student_view_attendance,
         name='student_view_attendance'),
    path("student/view/profile/", student_views.student_view_profile,
         name='student_view_profile'),
    path("student/fcmtoken/", student_views.student_fcmtoken,
         name='student_fcmtoken'),
    path('student/view/result/', student_views.student_view_result,
         name='student_view_result'),

]

main_app/forms.py
from django import forms
from django.forms.widgets import DateInput, TextInput

import json
from .models import *


class FormSettings(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FormSettings, self).__init__(*args, **kwargs)
        # Here make some changes such as:
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'


class CustomUserForm(FormSettings):
    email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'autocomplete': 'new-password'}))
    gender = forms.ChoiceField(choices=[('M', 'Male'), ('F', 'Female')])
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    address = forms.CharField(widget=forms.Textarea)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}))

    def __init__(self, *args, **kwargs):
        super(CustomUserForm, self).__init__(*args, **kwargs)
        
        
        if kwargs.get('instance'):
            instance = kwargs.get('instance').admin.__dict__
            self.fields['password'].required = False
            for field in CustomUserForm.Meta.fields:
                self.fields[field].initial = instance.get(field)
            if self.instance.pk is not None:
                self.fields['password'].widget.attrs['placeholder'] = "Fill this only if you wish to update password"

                

    def clean_email(self, *args, **kwargs):
        formEmail = self.cleaned_data['email'].lower()
        if self.instance.pk is None:  # Insert
            if CustomUser.objects.filter(email=formEmail).exists():
                raise forms.ValidationError(
                    "The given email is already registered")
        else:  # Update
            dbEmail = self.Meta.model.objects.get(
                id=self.instance.pk).admin.email.lower()
            if dbEmail != formEmail:  # There has been changes
                if CustomUser.objects.filter(email=formEmail).exists():
                    raise forms.ValidationError("The given email is already registered")

        return formEmail

    class Meta:
        fields = ['first_name', 'last_name', 'email', 'gender', 'address','password']


class StudentForm(CustomUserForm):
    subjects = forms.ModelMultipleChoiceField(queryset=Subject.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}))
    
    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        if kwargs.get('instance'):
            instance = kwargs.get('instance').admin.__dict__
            self.fields['subjects'].required = False
        subjects_choices = [
            (subject.id, f"{subject.name} - {subject.branch.name}")
            for subject in Subject.objects.all()
        ]
        self.fields['subjects'].choices = subjects_choices        

    class Meta(CustomUserForm.Meta):
        model = Student
        fields = ['rollno'] + CustomUserForm.Meta.fields + \
            ['branch', 'session','subjects']


class AdminForm(CustomUserForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),label="Update Password")
    def __init__(self, *args, **kwargs):
        super(AdminForm, self).__init__(*args, **kwargs)
        self.fields['address'].required = False
        


    class Meta(CustomUserForm.Meta):
        model = Admin
        fields = ['password','first_name', 'last_name', 'email', 'gender', 'address']
        


class StaffForm(CustomUserForm):
    def __init__(self, *args, **kwargs):
        super(StaffForm, self).__init__(*args, **kwargs)

    class Meta(CustomUserForm.Meta):
        model = Staff
        fields = CustomUserForm.Meta.fields + \
            ['branch','is_class_teacher']


class BranchForm(FormSettings):
    def __init__(self, *args, **kwargs):
        super(BranchForm, self).__init__(*args, **kwargs)

    class Meta:
        fields = ['name']
        model = Branch


class SubjectForm(FormSettings):

    def __init__(self, *args, **kwargs):
        super(SubjectForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Subject
        fields = ['name', 'staff', 'branch','session']


class SessionForm(FormSettings):
    def __init__(self, *args, **kwargs):
        super(SessionForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Session
        fields = '__all__'
        widgets = {
            'start_year': DateInput(attrs={'type': 'date'}),
            'end_year': DateInput(attrs={'type': 'date'}),
            'eight_weeks': DateInput(attrs={'type':'date'})
        }


class LeaveReportStaffForm(FormSettings):
    def __init__(self, *args, **kwargs):
        super(LeaveReportStaffForm, self).__init__(*args, **kwargs)

    class Meta:
        model = LeaveReportStaff
        fields = ['from_date','to_date', 'days','message']
        widgets = {
            'from_date': DateInput(attrs={'type': 'date'}),
            'to_date': DateInput(attrs={'type': 'date'}),
        }



class StudentEditForm(CustomUserForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),label="Update Password",initial="")
    def __init__(self, *args, **kwargs):
        super(StudentEditForm, self).__init__(*args, **kwargs)

    class Meta(CustomUserForm.Meta):
        model = Student
        fields = ['password','first_name','last_name','email','gender','address']


class StaffEditForm(CustomUserForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),label="Update Password",)
    def __init__(self, *args, **kwargs):
        super(StaffEditForm, self).__init__(*args, **kwargs)

    class Meta(CustomUserForm.Meta):
        model = Staff
        fields = ['password','first_name','last_name','email','gender','address','branch']


class EditResultForm(FormSettings):
    session_list = Session.objects.all()
    session_year = forms.ModelChoiceField(
        label="Semester", queryset=session_list, required=True)

    def __init__(self, *args, **kwargs):
        super(EditResultForm, self).__init__(*args, **kwargs)
    
    class Meta:
        model = StudentResult
        fields = ['session_year', 'subject', 'student', 'mid1', 'mid2', 'assg1', 'assg2']

class MarksReport(FormSettings):
    def __init__(self, *args, **kwargs):
        super(MarksReport,self).__init__(*args, **kwargs)
    
    class Meta:
        model=StudentResult
        fields = ['subject']

    

main_app/templates/staff_template/edit_student_result.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                    <form method="POST">
                        {% csrf_token %}
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

       
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">


                     

                 {{ form }}

                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" id='update_result' class="btn btn-primary btn-block">Update Result</button>
               
                    </div>
                </form>
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block custom_js %}
<script>
    $(document).ready(function () {
        $("#id_subject").change(function () {
            fetchStudents();
            });
            $("#id_session_year").change(function () {
                fetchStudents();
                });
   $("#id_student").change(function () {
    fetch_student_result();
                });
                $("#id_exam").hide()
                $("#id_test").hide()
                $("#update_result").hide()
                $('label[for="id_test"]').hide();
                $('label[for="id_exam"]').hide();
        function fetchStudents(){
            var subject = $("#id_subject").val()
            var session = $("#id_session_year").val()
            $("#id_student").html(null)
            if (session.length  == 0 || subject.length == 0 || session < 1 || subject < 1){
                return false;
            }
            $.ajax({
                url: "{% url 'get_students' %}",
                type: 'POST',
                data: {
                    subject: subject,
                    session:session
                }
            }).done(function (response) {
                var json_data = JSON.parse(response)
                if (json_data.length < 1) {
                    alert("No data to display")
                } else {
                    var div_data = "<option>Select Student</option>"

                    for (key in json_data) {
                        div_data += "<option value='" + json_data[key]['id'] + "'>" + json_data[key]['name'] + " </option>"
                    }
             
                    $("#id_student").html(div_data)
                }
            }).fail(function (response) {
                alert("Error in fetching students")
            })
               }

               function fetch_student_result(){
                var student = $("#id_student").val()
                var subject = $("#id_subject").val()
                $("#id_test").val(null)
                $("#id_exam").val(null)
                $("#id_exam").hide()
                $("#update_result").hide()
                $("#id_test").hide()
                $('label[for="id_test"]').hide();
                $('label[for="id_exam"]').hide();
                if (student.length  == 0 || subject.length == 0 || student < 1 || subject < 1){
                    return false;
                }
                $.ajax({
                    url: "{% url 'fetch_student_result' %}",
                    type: 'POST',
                    data: {
                        subject: subject,
                        student:student
                    }
                }).done(function (response) {
                    if (response == 'False') {
                        alert("No data to display")
                    } else {
                        var json_data = JSON.parse(response)
                        
                            $("#id_test").val(json_data['test'])
                            $("#id_exam").val(json_data['exam'])
                            $("#id_exam").show()
                            $("#id_test").show()
                            $("#update_result").show()
                            $('label[for="id_test"]').show();
                            $('label[for="id_exam"]').show();

                    }
                }).fail(function (response) {
                    alert("Error in fetching students")
                })
               }

    })
</script>
{% endblock custom_js %}

main_app/templates/staff_template/home_content.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>{{total_students}}</h3>

                        <p>Total Students</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-user-graduate"></i>
                    </div>
                   
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>{{total_leave}}</h3>
                        <p>Total Leaves Applied</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-calendar-alt"></i>
                    </div>
                   
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-maroon">
                    <div class="inner">
                        {% if leaves_left > 0 %}
                        <h3>{{leaves_left}}</h3>
                        {% else %}
                        <h3>0</h3>
                        {% endif %}
                        <p>Total CLs Left</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-calendar-alt"></i>
                    </div>
                   
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>{{total_subject}}</h3>

                        <p>Total Subjects</p>
                    </div>
                    <div class="icon">
                      <i class="nav-icon fas fa-book"></i>
                    </div>
                   
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->

    <div class="card card-default">
      <div class="card-header"><h3 class="card-title"><b>Leave Application Status</b></h3><br/>
        <div class="table">
  
         <table class="table table-bordered table-hover">
             <thead class="thead-dark">
              <tr>
                  <th>ID</th>
                  <th>Dates</th>
                  <th>Days</th>
                  <th>Message</th>
               <th>Status</th>
           </tr>
             </thead>
          {% for leave in leave_history %}
          <tr>
                <td>{{forloop.counter}}</td>
                {% if leave.from_date != leave.to_date %}
                <td>{{leave.from_date}} to {{leave.to_date}}</td>
                {% else %}
                <td>{{leave.from_date}}</td>
                {% endif %}
                <td>{{leave.days}}</td>
                <td>{{leave.message}}</td>
                <td>
                    
                    {% if leave.status == 0 %}
                    <span class="badge badge-warning">Pending</span>
                    {% elif leave.status == 1 %}
                    <span class="badge badge-success">Accepted</span>
                    
                      {% else %}
                      <span class="badge badge-danger">Rejected</span>
                      
                      {% endif %}
                      
                  </td>
              </tr>
              {% endfor %}
          </table>
        </div>
      </div>
    </div>
  
</section>
{% endblock content %}

{% block custom_js %}
      <!-- The core Firebase JS SDK is always required and must be listed first -->
      <script src="https://www.gstatic.com/firebasejs/7.23.0/firebase-app.js"></script>

      <!-- TODO: Add SDKs for Firebase products that you want to use
       https://firebase.google.com/docs/web/setup#available-libraries -->
      <script src="https://www.gstatic.com/firebasejs/7.23.0/firebase-analytics.js"></script>
      <script src="https://www.gstatic.com/firebasejs/7.22.1/firebase-messaging.js"></script>
  
  
      <script>
          // Your web app's Firebase configuration
          // For Firebase JS SDK v7.20.0 and later, measurementId is optional
          var firebaseConfig = {
              apiKey: "AIzaSyBarDWWHTfTMSrtc5Lj3Cdw5dEvjAkFwtM",
              authDomain: "sms-with-django.firebaseapp.com",
              databaseURL: "https://sms-with-django.firebaseio.com",
              projectId: "sms-with-django",
              storageBucket: "sms-with-django.appspot.com",
              messagingSenderId: "945324593139",
              appId: "1:945324593139:web:03fa99a8854bbd38420c86",
              measurementId: "G-2F2RXTL9GT"
          };
          // Initialize Firebase
          firebase.initializeApp(firebaseConfig)
          const messaging = firebase.messaging();
          function InitializeFireBaseMessaging() {
              messaging
                  .requestPermission()
                  .then(function () {
                      console.log("Notification Permission");
                      return messaging.getToken();
                  })
                  .then(function (token) {
                      console.log("Token : " + token);
                      sendToServer(token);
                  })
                  .catch(function (reason) {
                      console.log(reason)
                  })
          }
          messaging.onMessage(function (payload) {
              const notificationOption = {
                  body: payload.notification.body,
                  icon: payload.notification.icon,
  
              }
              if (Notification.permission == 'granted') {
                  var notification = new Notification(payload.notification.title, notificationOption);
                  notification.onclick = function (event) {
                      event.preventDefault();
                      window.open(payload.notification.click_action, "_blank");
                      notification.close();
                  }
              }
              console.log(payload);
          });
          messaging.onTokenRefresh(function () {
              messaging.getToken()
                  .then(function (newToken) {
                      console.log("New Token : " + newToken);
                      sendToServer(newToken);

                  })
                  .catch(function (reason) {
                      console.log(reason)
                  })
          })
  
          function sendToServer(token){
            $.ajax({
              url: "{% url 'staff_fcmtoken' %}",
              type: 'POST',
              data: {
                  token: token,
              }
          }).done(function (response) {
   
             
          }).fail(function (response) {
          })

          }
          
          InitializeFireBaseMessaging();
      </script>
{% endblock custom_js %}

main_app/templates/staff_template/staff_add_result.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                    <form method="POST" id="sturesform">
                        {% csrf_token %}
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>
                    
       
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="card-body">

                        <div class="form-group">
                            <label>Subject</label>
                            <select name="subject" class="form-control" id='subject'>
                                <option value="">----</option>
                                {% for subject in subjects  %}
                                <option value="{{subject.id}}">{{subject.name}}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Choose Exam</label>
                            <select name="exam" id='exam' class="form-control">
                                <option value="">----</option>
                                <option value="mid1">Mid-term 1</option>
                                <option value="mid2">Mid-term 2</option>
                            </select>
                        </div>
                        
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="button" id='fetch_student' class="btn btn-primary btn-block">Fetch Students</button>
                        <input type="hidden" id="hiddeninput" name="hiddeninput" value="">
                        <input type="hidden" id="sturecords" name="sturecords" value="">
                        <div class="form-group" id="student_data">
                            

                        </div>
                        
                    </div>
                    
                </form>
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
</section>
{% endblock content %}

{% block custom_js %}
<script>
    
    $(document).ready(function () {
       
        $("#fetch_student").click(function () {
            var subject = $("#subject").val()
            var exam = $("#exam").val()
            $("#student_data").html(null)
            if (subject.length  == 0){
                alert("Please select subject");
                return false;
            }
                        $.ajax({
                            url: "{% url 'get_students' %}",
                            type: 'POST',
                            data: {
                                subject: subject,
                            }
                        }).done(function (response) {
                            var json_data = JSON.parse(response)
                            var inputElement = document.querySelector('input[name="hiddeninput"]');
                            if (json_data.length < 1) {
                                alert("No Students in this Class")
                            } else if(exam=="mid1") {
                                i=1
                                var div_data = "<hr/><table class='table table-bordered' name='student_results' id='student_results'><thead class='table-dark'><tr><td>Roll Number</td><td>Mid 1</td><td>Assignment 1</td></tr></thead><tbody>"
                                sturecords = []
                                for (key in json_data) {
                                    sturecords.push({'rollno':json_data[key]['rollno']})
                                    div_data += "<tr><td>"+json_data[key]['rollno']+"</td><td><input class='form-control' name='mid-"+i+"' placeholder='Maximum 40' max='40' min='0' required type='number' value=''/></td><td><input class='form-control' name='assg-"+i+"' placeholder='Maximum 8' max='8' min='0' required type='number' value=''/></td><td></tr>"
                                    i+=1
                                }
                                document.querySelector('input[name="hiddeninput"]').value = i-1;
                                document.querySelector('input[name="sturecords"]').value=JSON.stringify(sturecords);

                                div_data += "</tbody></table><button type='submit' id='save_result' class='btn btn-success'>Save Results</button>"
                                
                                $("#student_data").html(div_data)
                                
                            } else {
                                i=1
                                var div_data = "<hr/> <table class='table table-bordered table-hover' name='student_results' id='student_results'><thead class='table-dark'><tr><td>Roll Number</td><td>Mid 2</td><td>Assignment 2</td></tr></thead><tbody>"
                                sturecords = []
                                for (key in json_data) {
                                    sturecords.push({'rollno':json_data[key]['rollno']})
                                    div_data +="<tr><td>"+json_data[key]['rollno']+"</td><td><input class='form-control' name='mid-"+i+"' placeholder='Maximum 40' max='40' min='0' required type='number' /></td><td><input class='form-control' name='assg-"+i+"' placeholder='Maximum 8' max='8' min='0' required type='number' /></td></tr>"
                                    i+=1
                                }

                                document.querySelector('input[name="hiddeninput"]').value = i-1;
                                document.querySelector('input[name="sturecords"]').value=JSON.stringify(sturecords);

                                div_data += "</tbody></table><button id='save_result' class='btn btn-success' onclick='submitResult()' >Save Results</button>"
                                
                                

                                $("#student_data").html(div_data)
                                
                            }
                        }).fail(function (response) {
                            alert("Error in fetching students")
                        })

                        

        })
    })

    
</script>
{% endblock custom_js %}