main_app/urls.py
from django.urls import path

from main_app.EditResultView import EditResultView

from . import hod_views, staff_views, student_views, views

urlpatterns = [
    path("", views.login_page, name='login_page'),
    path("get_attendance", views.get_attendance, name='get_attendance'),
    path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("logout_user/", views.logout_user, name='user_logout'),
    path("admin/home/", hod_views.admin_home, name='admin_home'),
    path("staff/add", hod_views.add_staff, name='add_staff'),
    path("branch/add", hod_views.add_branch, name='add_branch'),
    path("send_staff_notification/", hod_views.send_staff_notification,
         name='send_staff_notification'),
    path("add_session/", hod_views.add_session, name='add_session'),
   
    path("admin_notify_staff", hod_views.admin_notify_staff,
         name='admin_notify_staff'),
    path("admin_view_profile", hod_views.admin_view_profile,
         name='admin_view_profile'),
    path("check_email_availability", hod_views.check_email_availability,
         name="check_email_availability"),
    path("session/manage/", hod_views.manage_session, name='manage_session'),
    path("session/edit/<int:session_id>",
         hod_views.edit_session, name='edit_session'),
    path("staff/view/leave/", hod_views.view_staff_leave, name="view_staff_leave",),
    path("attendance/view/", hod_views.admin_view_attendance,
         name="admin_view_attendance",),
    path("results/view/", hod_views.admin_view_results,
         name="admin_view_results",),
    path("attendance/fetch/", hod_views.get_admin_attendance,
         name='get_admin_attendance'),
    path("student/add/", hod_views.add_student, name='add_student'),
    path("subject/add/", hod_views.add_subject, name='add_subject'),
    path("staff/manage/", hod_views.manage_staff, name='manage_staff'),
    path("student/manage/", hod_views.manage_student, name='manage_student'),
    path("branch/manage/", hod_views.manage_branch, name='manage_branch'),
    path("subject/manage/", hod_views.manage_subject, name='manage_subject'),
    path("staff/edit/<int:staff_id>", hod_views.edit_staff, name='edit_staff'),
    path("staff/delete/<int:staff_id>",
         hod_views.delete_staff, name='delete_staff'),

    path("branch/delete/<int:branch_id>",
         hod_views.delete_branch, name='delete_branch'),

    path("subject/delete/<int:subject_id>",
         hod_views.delete_subject, name='delete_subject'),

    path("session/delete/<int:session_id>",
         hod_views.delete_session, name='delete_session'),

    path("student/delete/<int:student_id>",
         hod_views.delete_student, name='delete_student'),
    path("student/edit/<int:student_id>",
         hod_views.edit_student, name='edit_student'),
    path("branch/edit/<int:branch_id>",
         hod_views.edit_branch, name='edit_branch'),
    path("subject/edit/<int:subject_id>",
         hod_views.edit_subject, name='edit_subject'),
     #realtime filtering of subjects in takeattendance
     path('get_filtered_subjects/<int:branch_id>/', 
          hod_views.get_filtered_subjects, name='get_filtered_subjects'),




    # Staff
    path("staff/home/", staff_views.staff_home, name='staff_home'),
    path("staff/apply/leave/", staff_views.staff_apply_leave,
         name='staff_apply_leave'),
    path("staff/view/profile/", staff_views.staff_view_profile,
         name='staff_view_profile'),
    path("staff/attendance/take/", staff_views.staff_take_attendance,
         name='staff_take_attendance'),
    path("staff/attendance/update/", staff_views.staff_update_attendance,
         name='staff_update_attendance'),
    path("staff/get_students/", staff_views.get_students, name='get_students'),
    path("staff/fetch_results/",staff_views.fetch_results,name='fetch_results'),
    path("staff/attendance/fetch/", staff_views.get_student_attendance,
         name='get_student_attendance'),
    path("staff/attendance/save/",
         staff_views.save_attendance, name='save_attendance'),
    #path("staff/attendance/update/",
         #staff_views.update_attendance, name='update_attendance'),
    path("staff/attendance/report/",
         staff_views.staff_attendance_report, name='staff_attendance_report'),
    path("staff/fcmtoken/", staff_views.staff_fcmtoken, name='staff_fcmtoken'),
    path("staff/view/notification/", staff_views.staff_view_notification,
         name="staff_view_notification"),
    path("staff/result/add/", staff_views.staff_add_result, name='staff_add_result'),
    path("staff/result/edit/", EditResultView.as_view(),
         name='edit_student_result'),
    path('staff/result/fetch/', staff_views.fetch_student_result,
         name='fetch_student_result'),
    path('staff/result/report/',
         staff_views.staff_marks_report, name='staff_marks_report'),
     path('staff/result/midterms/',
         staff_views.staff_midterm_report, name='staff_midterm_report'),


    # Student
    path("student/home/", student_views.student_home, name='student_home'),
    path("student/view/attendance/", student_views.student_view_attendance,
         name='student_view_attendance'),
    path("student/view/profile/", student_views.student_view_profile,
         name='student_view_profile'),
    path("student/fcmtoken/", student_views.student_fcmtoken,
         name='student_fcmtoken'),
    path('student/view/result/', student_views.student_view_result,
         name='student_view_result'),

]

main_app/forms.py
from django import forms
from django.forms.widgets import DateInput, TextInput

import json
from .models import *


class FormSettings(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FormSettings, self).__init__(*args, **kwargs)
        # Here make some changes such as:
        for field in self.visible_fields():
            field.field.widget.attrs['class'] = 'form-control'


class CustomUserForm(FormSettings):
    email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'autocomplete': 'new-password'}))
    gender = forms.ChoiceField(choices=[('M', 'Male'), ('F', 'Female')])
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    address = forms.CharField(widget=forms.Textarea)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}))

    def __init__(self, *args, **kwargs):
        super(CustomUserForm, self).__init__(*args, **kwargs)
        
        
        if kwargs.get('instance'):
            instance = kwargs.get('instance').admin.__dict__
            self.fields['password'].required = False
            for field in CustomUserForm.Meta.fields:
                self.fields[field].initial = instance.get(field)
            if self.instance.pk is not None:
                self.fields['password'].widget.attrs['placeholder'] = "Fill this only if you wish to update password"

                

    def clean_email(self, *args, **kwargs):
        formEmail = self.cleaned_data['email'].lower()
        if self.instance.pk is None:  # Insert
            if CustomUser.objects.filter(email=formEmail).exists():
                raise forms.ValidationError(
                    "The given email is already registered")
        else:  # Update
            dbEmail = self.Meta.model.objects.get(
                id=self.instance.pk).admin.email.lower()
            if dbEmail != formEmail:  # There has been changes
                if CustomUser.objects.filter(email=formEmail).exists():
                    raise forms.ValidationError("The given email is already registered")

        return formEmail

    class Meta:
        fields = ['first_name', 'last_name', 'email', 'gender', 'address','password']


class StudentForm(CustomUserForm):
    subjects = forms.ModelMultipleChoiceField(queryset=Subject.objects.all(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control'}))
    
    def __init__(self, *args, **kwargs):
        super(StudentForm, self).__init__(*args, **kwargs)
        if kwargs.get('instance'):
            instance = kwargs.get('instance').admin.__dict__
            self.fields['subjects'].required = False
        subjects_choices = [
            (subject.id, f"{subject.name} - {subject.branch.name}")
            for subject in Subject.objects.all()
        ]
        self.fields['subjects'].choices = subjects_choices        

    class Meta(CustomUserForm.Meta):
        model = Student
        fields = ['rollno'] + CustomUserForm.Meta.fields + \
            ['branch', 'session','subjects']


class AdminForm(CustomUserForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),label="Update Password")
    def __init__(self, *args, **kwargs):
        super(AdminForm, self).__init__(*args, **kwargs)
        self.fields['address'].required = False
        


    class Meta(CustomUserForm.Meta):
        model = Admin
        fields = ['password','first_name', 'last_name', 'email', 'gender', 'address']
        


class StaffForm(CustomUserForm):
    def __init__(self, *args, **kwargs):
        super(StaffForm, self).__init__(*args, **kwargs)

    class Meta(CustomUserForm.Meta):
        model = Staff
        fields = CustomUserForm.Meta.fields + \
            ['branch','is_class_teacher']


class BranchForm(FormSettings):
    def __init__(self, *args, **kwargs):
        super(BranchForm, self).__init__(*args, **kwargs)

    class Meta:
        fields = ['name']
        model = Branch


class SubjectForm(FormSettings):

    def __init__(self, *args, **kwargs):
        super(SubjectForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Subject
        fields = ['name', 'staff', 'branch','session']


class SessionForm(FormSettings):
    def __init__(self, *args, **kwargs):
        super(SessionForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Session
        fields = '__all__'
        widgets = {
            'start_year': DateInput(attrs={'type': 'date'}),
            'end_year': DateInput(attrs={'type': 'date'}),
            'eight_weeks': DateInput(attrs={'type':'date'})
        }


class LeaveReportStaffForm(FormSettings):
    def __init__(self, *args, **kwargs):
        super(LeaveReportStaffForm, self).__init__(*args, **kwargs)

    class Meta:
        model = LeaveReportStaff
        fields = ['from_date','to_date', 'days','message']
        widgets = {
            'from_date': DateInput(attrs={'type': 'date'}),
            'to_date': DateInput(attrs={'type': 'date'}),
        }



class StudentEditForm(CustomUserForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),label="Update Password",initial="")
    def __init__(self, *args, **kwargs):
        super(StudentEditForm, self).__init__(*args, **kwargs)

    class Meta(CustomUserForm.Meta):
        model = Student
        fields = ['password','first_name','last_name','email','gender','address']


class StaffEditForm(CustomUserForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),label="Update Password",)
    def __init__(self, *args, **kwargs):
        super(StaffEditForm, self).__init__(*args, **kwargs)

    class Meta(CustomUserForm.Meta):
        model = Staff
        fields = ['password','first_name','last_name','email','gender','address','branch']


class EditResultForm(FormSettings):
    session_list = Session.objects.all()
    session_year = forms.ModelChoiceField(
        label="Semester", queryset=session_list, required=True)

    def __init__(self, *args, **kwargs):
        super(EditResultForm, self).__init__(*args, **kwargs)
    
    class Meta:
        model = StudentResult
        fields = ['session_year', 'subject', 'student', 'mid1', 'mid2', 'assg1', 'assg2']

class MarksReport(FormSettings):
    def __init__(self, *args, **kwargs):
        super(MarksReport,self).__init__(*args, **kwargs)
    
    class Meta:
        model=StudentResult
        fields = ['subject']

    

main_app/templates/hod_template/add_branch_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">Add Branch</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Add Branch"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

main_app/templates/hod_template/add_session_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Add Semester"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

main_app/templates/hod_template/add_staff_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}
{% block custom_css %}
  <style>
      .invalid{
        font-style: italic;
        font-weight: bold;
        color: red;
      }
      .valid{
        font-style: italic;
        font-weight: bold;
        color: green;
      }
  </style>
{% endblock custom_css %}
{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Add Staff"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% block custom_js %}
<script>
    function validateEmail(email) {
        const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return re.test(String(email).toLowerCase());
    }
    $(document).ready(function(){
        $("#id_email").keyup(function(){
            
            var email = $(this).val()
            if (validateEmail(email)){
            $.ajax({
                url: "{% url 'check_email_availability' %}",
                type: 'POST',
                data:{email:email}
            }).done(function(response){
                if (response == "True"){
                    $(".email_error").remove()
                    $("<span class='invalid email_error'>Email Address Already Exist</span>").insertAfter("#id_email");
                }
                else{
                    $(".email_error").remove()
                    $("<span class='valid email_error'>Email Address Available</span>").insertAfter("#id_email");
                }
            }).fail(function(response){
                $("<span class='alert alert-warning'>Server Could Not Process This</span>").insertAfter("#id_email");
            })
        }
        })
    });
</script>
{% endblock custom_js %}

main_app/templates/hod_template/add_student_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block custom_css %}
  <style>
      .invalid{
        font-style: italic;
        font-weight: bold;
        color: red;
      }
      .valid{
        font-style: italic;
        font-weight: bold;
        color: green;
      }
  </style>
{% endblock custom_css %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Add Student"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% block custom_js %}
<script>
    function validateEmail(email) {
        const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return re.test(String(email).toLowerCase());
    }
    $(document).ready(function(){
        $("#id_subjects").prop('disabled', true);
        $("#id_email").keyup(function(){
            
            var email = $(this).val()
            if (validateEmail(email)){
            $.ajax({
                url: "{% url 'check_email_availability' %}",
                type: 'POST',
                data:{email:email}
            }).done(function(response){
                if (response == "True"){
                    $(".email_error").remove()
                    $("<span class='invalid email_error'>Email Address Already Exist</span>").insertAfter("#id_email");
                }
                else{
                    $(".email_error").remove()

                    $("<span class='valid email_error'>Email Address Available</span>").insertAfter("#id_email");
                }
            }).fail(function(response){
                $("<span class='alert alert-warning'>Server Could Not Process This</span>").insertAfter("#id_email");
            })
        }
        })

        $('#id_branch, #id_session').change(function() {
            var branchId = $('#id_branch').val();
            var sessionId = $('#id_session').val();
            if (branchId && sessionId) {
                $.ajax({
                    url: '/get_filtered_subjects/' + branchId + '/',
                    type: 'GET',
                    data: {
                        session_id: sessionId  
                    },
                    dataType: 'json',
                    success: function(data) {
                        $("#id_subjects").prop('disabled', false);
                        var subjectsSelect = $('#id_subjects');
                        subjectsSelect.empty();
                        $.each(data.subjects, function(index, subject) {
                            subjectsSelect.append('<option value="' + subject.id + '">' + subject.name + '</option>');
                        });
                    }
                });
            }
        });
    });
</script>
{% endblock custom_js %}

main_app/templates/hod_template/add_subject_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Add Subject"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

main_app/templates/hod_template/admin_view_attendance.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}
<script src="{% static 'printreport.js' %}"></script>

<!--CDN to convert HTML table to excel-->
<script type="text/javascript" src="https://unpkg.com/xlsx@0.15.1/dist/xlsx.full.min.js"></script>
<!--CDN to convert HTML table to PDF || source: pdfmake-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.68/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.68/vfs_fonts.js"></script>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    
                    <div class="card-header">
                        <div class="form-inline">
                            <select id="mySemester" onchange="myFunction3()" class="form-control form-select">
                              <option value="">-- Select Semester --</option>
                              {% for s in sessions %}
                                  <option value="{{s.name}}">{{s.name}}</option>
                              {% endfor %}
                            </select>
                            <div style="padding:10px"></div>
                            <select id="myBranch" onchange="myFunction1()" class="form-control form-select">
                              <option value="">-- Select Branch --</option>
                              {% for b in branches %}
                                  <option value="{{b.name}}">{{b.name}}</option>
                              {% endfor %}
                            </select>
                            <div style="padding:10px"></div>
                            <input id="myRno" type="text" placeholder="Enter Roll Number..." onkeyup="myFunction2()" class="form-control" title="Enter a Roll Number">
                        </div>
                        
                    </div>
                    <!-- /.card-header -->
                    
                    <div class="card-body">
                        <table id="reporttable" class="table table-bordered table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th style="display:none">Semester</th>
                                    <th>Branch</th>
                                    <th>Roll No</th>
                                    <th>Full Name</th>
                                    <th>Attendance</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for att in attendance %}
                                
                                    <tr>
                                        <td style="display:none">{{att.student.session}}</td>
                                        <td>{{att.student.branch}}</td>
                                        <td>{{att.student.rollno}}</td>
                                        <td>{{att.student.admin.last_name}} {{att.student.admin.first_name}}</td>
                                        <td>{{att.present_percentage}}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table><br/>
                        <button class="btn btn-success" onclick="get_excel('xlsx','reporttable')">Download Spreadsheet</button>
                        <button class="btn btn-info" onclick="get_pdf('reporttable')">Generate Report</button>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <script>
        function get_excel(type,name,fn,dl)
        {
            var elt = document.getElementById(name);
            var wb = XLSX.utils.table_to_book(elt, { sheet: "sheet1" });
            return dl ?
                XLSX.write(wb, { bookType: type, bookSST: true, type: 'base64' }) :
                XLSX.writeFile(wb, fn || ('Attendance_Report.' + (type || 'xlsx')));
        }

        function get_pdf(name) {
          //extracting the table data
          const filteredData = [];
          const tableRows = document.getElementById('reporttable').getElementsByTagName('tbody')[0].getElementsByTagName('tr');
          for (const row of tableRows) {
              if (row.style.display !== 'none') {
                  const rowData = [];
                  for (const cell of row.cells) {
                      rowData.push(cell.innerText);
                  }
                  filteredData.push(rowData);
              }
          }
          const currentDate = new Date().toLocaleDateString();
          
          //generating the pdf
          const docDefinition = {
            header: {text:'College Name\nDepartment of ET',alignment:'center',style:'header'},
            footer: function(currentPage,pageCount) { return ({text: `Page ${currentPage} of ${pageCount}`,alignment:'center',style:'footer'});},
            content: [
             
              {text: 'Attendance Report', style:'heading',alignment:'center'},
              {text: `Date: ${currentDate}`,alignment:'center'},
              { 
                table: {
                  widths:['*','*','*','*'],
                  
                  headerRows: 1,
                  body: [
                    ['Branch','Roll Number','Student Name','Attendance %'],
                    ...filteredData.map(Object.values)
                  ]
                },
                layout: {
                  fillColor: function(rowIndex) {
                    if (rowIndex === 0) {
                      return '#e3e3e3';
                    }
                  }
                },

              }
            ],
            styles: {
              heading: {
                  fontSize: 18,
                  bold: true,
                  margin: [0, 0, 0, 10],
              },
              header: {
                fontSize: 10,
                color: '#888888',
                margin: [0,5,0,0]
              },
              footer: {
                fontSize:10,
                color: '#888888'
              },
              

          }
          };
          pdfMake.createPdf(docDefinition).open();
        }
                
        function myFunction1() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myBranch");
            filter = input.value.toUpperCase();
            table = document.getElementById("reporttable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
              td = tr[i].getElementsByTagName("td")[1];
              if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                  tr[i].style.display = "";
                } else {
                  tr[i].style.display = "none";
                }
              }       
            }
            myFunction2()
          }

          function myFunction2() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myRno");
            filter = input.value.toUpperCase();
            table = document.getElementById("reporttable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
              td = tr[i].getElementsByTagName("td")[2];
              if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                  tr[i].style.display = "";
                } else {
                  tr[i].style.display = "none";
                }
              }       
            }
            myFunction1()
          }

          function myFunction3() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("mySemester");
            filter = input.value.toUpperCase();
            table = document.getElementById("reporttable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
              td = tr[i].getElementsByTagName("td")[0];
              if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                  tr[i].style.display = "";
                } else {
                  tr[i].style.display = "none";
                }
              }       
            }
          }
    </script>
</section>


{% endblock content %}

main_app/templates/hod_template/edit_branch_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">Edit Branch</h3>
                    </div>

                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Edit Branch"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}

main_app/templates/hod_template/edit_staff_template.html
{% extends 'main_app/base.html' %}
{% load static %}
{% block page_title %}{{page_title}}{% endblock page_title %}

{% block content %}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-dark">
                    <div class="card-header">
                        <h3 class="card-title">{{page_title}}</h3>
                    </div>
                    {% include "main_app/form_template.html" with messages=messages  form=form button_text="Update Staff"%}
                </div>
                <!-- /.card -->

            </div>
        </div>
    </div>
</section>
{% endblock content %}